spring.application.name=se302

spring.datasource.url=jdbc:postgresql://ep-sweet-wildflower-alonhxh2-pooler.c-3.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_4IOsj3WdXzEk

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.driver-class-name=org.postgresql.Driver

spring.mvc.throw-exception-if-no-handler-found=true